Dev (#16)
* Changing yaml requirement to test fix

* otra vez

* more fixes...

* Another tweak

* Fixes v4

* Fixes v6

* fixes v7

* Fixes v8...

* Fixes v8

* Yaml lint approved...

* Getting closer

* One more tweak

* (Hopefully) final fixes to gh actions yamls

* Lintin changes using black and prettier

* Html fixes. The linter seems to have broken some of the html syntax.

* Adding an app for the landing page as well as views for the front end

* Adding in the __init__.py file

* Adding a dashboard app

* Adding changes to the landing view

* Styling changes

* Pushing old workflow yamls - for posterity I guess...

* Adding some styling changes

* Adding dashboard html files

* Adding small change to env.sample

* Adding README.md v1

* PR for first tranche of enhancement features into dev. (#14)

* Removing stock flowbite image

* Removing superfluous sprints

* Adding planned enhancements README.md

* Adding pre commit hooks.

* Updates to enhancements to do list

* Adding format changes by ruff

* Adding auth changes suggested by ruff

* Adding visits changes suggested by ruff

* Adding updates to ignore files

* Adding pre-commit to requirements.txt

* Adding customers changes suggested by ruff

* Adding core project changes suggested by ruff

* Adding dashboard changes suggested by ruff

* Adding changes suggested by ruff in one fell swoop.

* Adding pre-commit config jsons

* Updating and improving github workflow yamls

* Updating Enhancements

* Adding updates to enhancements README.md

* Docstrings and hint types for core project file.

* Docstrings and hint types for auth views

* Fixing pre-commit hooks and reflecting in files.

* More docstrings and improvements

* Docstrings for commander class

* Fixing docstrings for billing

* Adding docstrings and typehints to profiles

* Adding docstrings and typehints to subscription maangement commands

* Adding docstrings and typehints to subscription views

* Adding docstrings and typehints to subscription utils

* Adding docstrings and typehints to dashboard views

* Adding default currency to settings

* Adding doc strings to Subscription admin

* Adding doc strings to the PageVisist model

* Adding updates to customers and subscriptions

* Last set of doc strings and type hints

* Switching dependency management to poetry

* Adding poetry lock and poetry toml files

* Updating gh workflows from requirements.txt to poetry

* Reflecting progress on enhancements/README.md

* Implementing a project level logger

* Logging helpers

* More logging updates

* Logging in the subscriptions app

* Updating enhancements/README.md

* Feat/enhancements v2 (#15)

* Removing superfluous Dockerfile.old

* Refactoring subscriptions utils

* Refactoring checkout views.

* Removing superfluous package jsons since I'm not using prettier

* Adding update to enhancements/README.md

* Update env.sample to reflect currency change.

* Small tweak to views to avoid logger error.

* Small updates to ignore files

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,11 +1,25 @@
 name: scheduled-production-workflows
 on:
-  workflow_dispatch: # Means I can run this at any time
+  workflow_dispatch:
+    inputs:
+      db_test:
+        description: 'Schedule type'
+        required: false
+        default: false
   schedule:
-    - cron: '0 1 20 * * ' # Every 20th day of the month at 1:00 AM UTC
-    - cron: '1 0 1 * * '  # 1st day of the month at 0:01 AM UTC
+    - cron: '0 1 20 * *' # Clean up every 20th day of the month at 01:00 AM UTC
+    - cron: '1 0 1 * *'  # Sync User Subs every 1st day of the month at 00:01 AM UTC
 jobs:
+  setup-environment:
+    runs-on: ubuntu-latest
+    uses: ./.github/workflows/setup-python-node-neon.yaml
+    with:
+      python-version: '3.12'
+      node-version: '20'
+  
   tidy_up:
+    name: Tidy Up Environment and Syncronise Subscriptions
+    needs: setup-environment
     runs-on: ubuntu-latest
     env:
       DJANGO_DEBUG: 0
@@ -14,43 +28,64 @@ jobs:
       NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
       NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
       NEON_PROD_BRANCH: "main"
+      SCHEDULE_TYPE: ${{ github.event_name == 'schedule' }}
+    
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.12'
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: "18"
-      - name: Install Neon CLI
-        run: |
-          npm install -g neonctl
+      
       - name: Grab Database URL
         run: |
           DB_CONNECTION_STRING=$(neonctl connections-string --branch "${{ env.NEON_PROD_BRANCH }}" --project-id "${{ env.NEON_PROJECT_ID }}")
+          if [ -z "$DB_CONNECTION_STRING" ]; then
+            echo "Database URL could not be retrieved. Exiting..."
+            exit 1
+          fi
           echo "DATABASE_URL=$DB_CONNECTION_STRING" >> $GITHUB_ENV
+      
+      - name: Test Database Connection
+        if: github.event_name == 'workflow_dispatch' && github.event.inputs.db_test == 'true'
+        run: |
+          echo "Testing database connection..."
+          python -c "import psycopg2; conn = psycopg2.connect('${{ env.DATABASE_URL }}'); print('DB Connection Successful')"
+
+      - name: Print Connection Successful!
+        if: github.event_name == 'workflow_dispatch' && github.event.inputs.db_test == 'true'
+        run: echo "Successfully Connected to DB"
+      
       - name: Setup Django Secret Key
         run: |
           GENERATED_KEY=$(openssl rand -base64 32)
           echo "DJANGO_SECRET_KEY=$GENERATED_KEY" >> $GITHUB_ENV
-      - name: Install Requirements
+      
+      # - name: Install Python Requirements
+      #   run: |
+      #     python -m pip install pip --upgrade
+      #     python -m pip install -r requirements.txt
+
+      - name: Install Poetry
         run: |
-          python -m pip install pip --upgrade
-          python -m pip install -r requirements.txt
-      - name: Make Django DB Migrations
+          python -m pip install --upgrade pip
+          python -m pip install poetry
+
+      - name: Install Dependencies with Poetry
+        run: |
+          poetry install --no-interaction --no-ansi
+      
+      - name: Apply Django DB Migrations
         working-directory: ./src
         run: |
           python manage.py migrate
-      - name: User Syncronisation Command
-        if: github.event.schedule == '1 0 1 * * *'
+      
+      
+      - name: Synchronise User Subscriptions
+        if: env.SCHEDULE_TYPE && startsWith(github.event.cron, '1 0 1 * *')
         working-directory: ./src
         run: |
           python manage.py sync_user_subscriptions --verbose --from-days 0 --to-days 1
-      - name: Clear Dangling Stripe Subscriptions Commands
-        if: github.event.schedule == '0 1 20 * * *'
+      
+      - name: Clear Unmatched Stripe Subscriptions Commands
+        if: env.SCHEDULE_TYPE && startsWith(github.event.cron, '0 1 20 * *')
         working-directory: ./src
         run: |
           python manage.py sync_user_subscriptions --clear-dangling
